In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.__version__

'2.3.2'

In [3]:
data = pd.read_csv("/Users/pranayrastogi/PycharmProjects/ML_Zoomcamp/data/car_fuel_efficiency.csv")

In [4]:
data.shape

(9704, 11)

In [6]:
data.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [8]:
data.fuel_type.nunique()

2

In [9]:
data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [11]:
data[data.origin=="Asia"]["fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

In [22]:
data["horsepower"].quantile(0.50)

np.float64(149.0)

In [24]:
data["horsepower"].value_counts().index[0]

np.float64(152.0)

In [26]:
data.horsepower.isnull().sum()

np.int64(708)

In [29]:
data.horsepower.fillna(data["horsepower"].value_counts().index[0],inplace=True)

In [30]:
data["horsepower"].quantile(0.50)

np.float64(152.0)

In [43]:
asian_cars = data[data.origin=="Asia"]
asian_cars = asian_cars.reset_index(drop=True)
asian_cars.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  250            1.0       174.0     2714.219310   
1                  320            5.0       145.0     2783.868974   
2                  200            6.0       160.0     3582.687368   
3                  150            3.0       197.0     2231.808142   
4                  160            4.0       133.0     2659.431451   

   acceleration  model_year origin fuel_type         drivetrain  num_doors  \
0          10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
1          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
2          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
3          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
4           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

   fuel_efficiency_mpg  
0            16.823554  
1            16.175820  
2            11.871091  
3            18.889083  
4            16.077730

In [44]:
asian_cars = asian_cars[["vehicle_weight", "model_year"]]
X = asian_cars.head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [45]:
X.shape

(7, 2)

In [46]:
XTX = X.T.dot(X)
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [49]:
XTX.shape

(2, 2)

In [50]:
inv_X = np.linalg.inv(XTX)
inv_X

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [51]:
XTy = X.T.dot(y)
XTy

array([21781922.71260447, 14900300.        ])

In [53]:
w = inv_X.dot(XTy)

In [54]:
np.sum(w)

np.float64(0.5187709081074008)